"""empty message

Revision ID: 2f058403e5f8
Revises: e0a6129dde7c
Create Date: 2021-11-24 13:09:16.028107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f058403e5f8'
down_revision = 'e0a6129dde7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'test_date')
    op.alter_column('teachers', 'years_teaching',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'years_teaching',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('scores', sa.Column('test_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
